# Generated by Django 5.1.6 on 2025-06-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
