# Generated by Django 5.1.6 on 2025-06-09 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_teachermodel_kafedra_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafedrafanmodel',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teachermodel'),
        ),
    ]
